spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fams?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.10.11.254
    port: 6379
    password: Ff17301576208
    database: 0
    jedis:
      pool:
        #?????
        max-active: 8
        #????????(???????)
        max-wait: -1
        #????
        max-idle: 8
        #????
        min-idle: 0
        #??????
    timeout: 10000


server:
  port: 8808